---
# tasks file for k8s_slave


- name: "Installing docker"
  package:
    name: "docker"
    state: present 

- name: "Enabelling docker services"
  service:
    name: "docker"
    state: started
    enabled: yes

- name: "Creating file"
  shell: "touch /etc/yum.repos.d/kubernetes.repo"

- name: "configuring kubernetes repo"
  blockinfile:
    path: "/etc/yum.repos.d/kubernetes.repo"
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: "Creating file"
  shell: "touch /etc/docker/daemon.json"

- name: "Docker driver updating"
  blockinfile:
    path: "/etc/docker/daemon.json"
    block: |
      {
          "exec-opts": ["native.cgroupdriver=systemd"]
      }

- name: "Kubernetes Installation"
  package:
    name: "kubelet"
    state: present

- name: "Kubernetes Installation"
  package:
    name: "kubeadm"
    state: present

- name: "Kubernetes Installation"
  package:
    name: "kubectl"
    state: present


- name: "iproute-tc installation"
  package:
    name: "iproute-tc"
    state: present

- name: "creating file"
  shell: "touch /etc/sysctl.d/k8s.conf"

- name: "Kubernetes configuration"
  blockinfile:
    path: "/etc/sysctl.d/k8s.conf"
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: "starting system service"
  shell: "sysctl --system"

- name: "Kubelet service starting"
  service:
    name: "kubelet"
    state: started
    enabled: yes

- name: "Pulling kubernetes images"
  shell: "kubeadm config images pull"

- name: "Kubernet Initailising..."
  shell:
   cmd: "kubeadm init --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
  ignore_errors: yes

- name: "kubeadm reset..."
  shell:
    cmd: "echo y | kubeadm reset" 

- name: "Token Copy..."
  copy:
   src: "token.txt"
   dest: "/root/token.txt"

- name: "Join..."
  shell:
   cmd: "bash /root/token.txt"
  ignore_errors: yes
